version: '3.5'

services:

  postgres-1:
    image: ntw/postgres
    container_name: postgres-1
    hostname: postgres-1
    network_mode: "host"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./logs/postgres:/var/log/postgresql
      - ./data/postgres:/var/lib/postgresql/data
    command: postgres -c shared_buffers=128MB -c max_connections=50


  eureka-1:
    image: ntw/eureka
    container_name: eureka-1
    hostname: eureka-1
    network_mode: "host"
    environment:
      - JAVA_OPTIONS=-Xmx512M
      - server.port=8761
      - eureka.server.enableSelfPreservation=false
      - eureka.server.responseCacheUpdateInvervalMs=50000
      - eureka.server.evictionIntervalTimerInMs=10000
    volumes:
      - ./logs/eureka:/usr/local/tomcat/logs


  lb-web-1:
    image: ntw/lb-web
    container_name: lb-web-1
    hostname: lb-web-1
    network_mode: "host"
    environment:
      - SERVER_HOSTS=web-1
      - SERVER_PORT=8000
      - USE_SSL=true
    volumes:
      - ./logs/lb-web-1:/var/log/oms


  web-1:
    image: ntw/web
    container_name: web-1
    hostname: web-1
    network_mode: "host"
    env_file: .env
    environment:
      - REST_HOST=lb-rest-1
      - REST_PORT=80
    volumes:
      - ./logs/web:/var/log/oms
    command: python3 manage.py runserver 0.0.0.0:8000


  lb-rest-1:
    image: ntw/lb-rest
    container_name: lb-rest-1
    hostname: lb-rest-1
    network_mode: "host"
    environment:
      - SERVER_HOSTS=gateway-svc-1
      - SERVER_PORT=8080
    volumes:
      - ./logs/lb-rest-1:/var/log/oms


  gateway-svc-1:
    image: ntw/rest
    container_name: gateway-svc-1
    hostname: gateway-svc-1
    network_mode: "host"
    env_file: .env
    environment:
      - server.threadPool.threads.maximum=20
    volumes:
      - ./logs/gateway-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh GatewaySvc

  admin-svc-1:
    image: ntw/rest
    container_name: admin-svc-1
    hostname: admin-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/admin-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh AdminSvc

  auth-svc-1:
    image: ntw/rest
    container_name: auth-svc-1
    hostname: auth-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/auth-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh AuthSvc

  user-profile-svc-1:
    image: ntw/rest
    container_name: user-profile-svc-1
    hostname: user-profile-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/user-profile-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh UserProfileSvc

  product-svc-1:
    image: ntw/rest
    container_name: product-svc-1
    hostname: product-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/product-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh ProductSvc

  order-svc-1:
    image: ntw/rest
    container_name: order-svc-1
    hostname: order-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/order-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh OrderSvc

  inventory-svc-1:
    image: ntw/rest
    container_name: inventory-svc-1
    hostname: inventory-svc-1
    network_mode: "host"
    env_file: .env 
    volumes:
      - ./logs/inventory-svc:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh InventorySvc
