---
apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  labels:
    app: admin-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: admin-svc-nodes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-svc-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-svc-nodes
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: admin-svc-nodes
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra; do echo waiting for cassandra; sleep 1; done;' ]
      - name: wait-for-postgres
        image: postgres
        command: [ '/bin/bash','-c', 'until pg_isready -h postgres; do echo waiting for postgres; sleep 1; done;' ]
      containers:
      - name: admin-svc-cont
        image: IMAGE_REGISTRY_PATH/rest:REVISION_ID
        args: ["AdminSvc"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "768Mi"
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: ALL
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.password
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
