---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: auth-svc-nodes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc-nodes
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-svc-nodes
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra; do echo waiting for cassandra; sleep 1; done;' ]
      containers:
      - name: auth-svc-cont
        image: IMAGE_REGISTRY_PATH/rest:REVISION_ID
        args: ["AuthSvc"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1024Mi"
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: CQL
#          - name: auth.password.plain
#            value: "true"
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-svc-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-svc-nodes
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
