---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  labels:
    app: inventory-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: inventory-svc-nodes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-svc-nodes
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: inventory-svc-nodes
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres
        command: [ '/bin/bash','-c', 'until pg_isready -h postgres; do echo waiting for postgres; sleep 1; done;' ]
      containers:
      - name: inventory-svc-cont
        image: IMAGE_REGISTRY_PATH/rest:REVISION_ID
        args: ["InventorySvc"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "768Mi"
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: SQL
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.password
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-svc-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-svc-nodes
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
