---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: default
  selector:
    app: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-1
  labels:
    app: postgres
spec:
  containers:
    - name: postgres-1
      image: IMAGE_REGISTRY_PATH/postgres:REVISION_ID
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 5432
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
          subPath: postgres
      readinessProbe:
        exec:
           command:
           - /bin/bash
           - -c
           - /check-readiness.sh
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: postgres.user
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: postgres.password
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: local-disk-postgres-claim
