---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32100
  selector:
    app: web-app-nodes
#  type: LoadBalancer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-nodes
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app-nodes
    spec:
      containers:
      - name: web-app-static-cont
        image: IMAGE_REGISTRY_PATH/lb-web:REVISION_ID
        imagePullPolicy: Always
        ports:
          - containerPort: 80      
        env:
          - name: WEB_HOSTS
            value: localhost
          - name: WEB_PORT
            value: "8000"
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - name: web-app-dynamic-cont
        image: IMAGE_REGISTRY_PATH/web:REVISION_ID
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: web-config
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 2
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
      volumes:
        - name: log-data
          emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app-nodes
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
