---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: default
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  serviceName: "cassandra"
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: ntw/cassandra
          imagePullPolicy: Never      
          ports:
            - protocol: TCP
              containerPort: 9042
          readinessProbe:
            exec:
               command:
               - /bin/bash
               - -c
               - /check-readiness.sh
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: cassandra-config
          env:
            - name: MAX_HEAP_SIZE
              value: 1024M
            - name: HEAP_NEWSIZE
              value: 512M
          volumeMounts:
            - mountPath: "/var/lib/cassandra"
              name: cassandra-storage
#      volumes:
#        - name: cassandra-storage
#          persistentVolumeClaim:
#            claimName: local-disk-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: cassandra-storage
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 32Mi
