---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: gateway-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc  
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra; do echo waiting for cassandra; sleep 1; done;' ]
      - name: wait-for-postgres
        image: postgres
        command: [ '/bin/bash','-c', 'until pg_isready -h postgres; do echo waiting for postgres; sleep 1; done;' ]
      containers:
      - name: gateway
        image: ntw/rest
        args: ["GatewaySvc"]
        imagePullPolicy: Never
#        resources:
#          requests:
#            cpu: "50m"
#            memory: "512Mi"
#          limits:
#            cpu: "200m"
#            memory: "768Mi"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.user
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.password
          - name: JAVA_OPTIONS
            value: "-Xms256M -Xmx768M -XX:NewRatio=1 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=1"
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 3
#      - name: flume
#        image: asia.gcr.io/PROJECT_ID/flume:REVISION_ID
#        volumeMounts:
#          - name: log-data
#            mountPath: /var/log/oms
      volumes:
        - name: log-data
          emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-scale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
