---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: web
#  type: LoadBalancer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web  
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: lb-web
        image: ntw/lb-web
        imagePullPolicy: Never
        ports:
          - containerPort: 80      
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
          - name: WEB_HOSTS
            value: localhost
          - name: WEB_PORT
            value: "8000"
      - name: web
        image: ntw/web
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
#        resources:
#          requests:
#            cpu: "250m"
#            memory: "250Mi"
#          limits:
#            cpu: "500m"
#            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: web-config
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
#      - name: flume
#        image: asia.gcr.io/PROJECT_ID/flume:REVISION_ID
#        volumeMounts:
#          - name: log-data
#            mountPath: /var/log/oms
      volumes:
        - name: log-data
          emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-scale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
